const products = [
  {
    name: "T-shirt with Tape Details",
    description: "Comfortable cotton t-shirt with premium quality fabric.",
    price: 120,
    discountPrice: 100,
    rating: 4.5,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    category: "Casual",
    dressStyle: "Casual",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White"],
    isTopSelling: false,
    isNewArrival: true,
  },
  {
    name: "Skinny Fit Jeans",
    description: "Stylish skinny fit jeans perfect for everyday wear.",
    price: 240,
    discountPrice: 210,
    rating: 4.3,
    reviews: 95,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    category: "Casual",
    dressStyle: "Casual",
    sizes: ["30", "32", "34"],
    colors: ["Blue"],
    isTopSelling: true,
    isNewArrival: true,
  },
  {
    name: "Checkered Shirt",
    description: "Formal checkered shirt for office and events.",
    price: 180,
    discountPrice: 150,
    rating: 4.7,
    reviews: 200,
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=800&q=80",
    category: "Formal",
    dressStyle: "Formal",
    sizes: ["M", "L", "XL"],
    colors: ["Red", "Black"],
    isTopSelling: true,
    isNewArrival: false,
  },
  {
    name: "Orange Graphic T-Shirt",
    description: "Trendy graphic t-shirt with modern design.",
    price: 160,
    discountPrice: 130,
    rating: 4.4,
    reviews: 145,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    category: "Party",
    dressStyle: "Party",
    sizes: ["S", "M", "L"],
    colors: ["Orange"],
    isTopSelling: true,
    isNewArrival: false,
  },
  {
    name: "Vertical Striped Shirt",
    description: "Elegant vertical striped shirt with classy styling.",
    price: 220,
    discountPrice: 190,
    rating: 4.6,
    reviews: 170,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80",
    category: "Formal",
    dressStyle: "Formal",
    sizes: ["M", "L"],
    colors: ["Green"],
    isTopSelling: false,
    isNewArrival: true,
  },
  {
    name: "Loose Fit Bermuda Shorts",
    description: "Relaxed fit shorts ideal for summer days.",
    price: 140,
    discountPrice: 110,
    rating: 4.2,
    reviews: 88,
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=800&q=80",
    category: "Gym",
    dressStyle: "Gym",
    sizes: ["M", "L", "XL"],
    colors: ["Blue"],
    isTopSelling: false,
    isNewArrival: true,
  },
];

module.exports = products;